"""added column open ai key on course table

Revision ID: 041cce36f324
Revises: 7587ce9ee7bf
Create Date: 2024-06-20 12:16:46.835224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '041cce36f324'
down_revision = '7587ce9ee7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.drop_column('openai_key')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('openai_key')

    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_key', mysql.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
