"""Added column unsubscribeconfirm in table user

Revision ID: 55167b0aee52
Revises: 041cce36f324
Create Date: 2024-07-04 19:58:31.910348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55167b0aee52'
down_revision = '041cce36f324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubsciption_reason', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unsubsciption_reason')

    # ### end Alembic commands ###
