"""added column type on course table

Revision ID: 7587ce9ee7bf
Revises: b80eb1f43bc8
Create Date: 2024-06-20 04:52:46.995136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7587ce9ee7bf'
down_revision = 'b80eb1f43bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
