"""Added product_id and endpoint_secret to Course model

Revision ID: e063ee73bfb5
Revises: 
Create Date: 2024-06-12 13:50:26.523191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e063ee73bfb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('endpoint_secret')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('endpoint_secret', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
